# Generated by Django 6.0.3 on 2026-03-15 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, help_text='Уникальный идентификатор записи во внешней системе', max_length=255, unique=True, verbose_name='External ID')),
                ('user_id', models.CharField(help_text='Идентификатор пользователя', max_length=255, verbose_name='User ID')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('subject', models.CharField(max_length=500, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'indexes': [models.Index(fields=['external_id'], name='mailings_ma_externa_6f2b1c_idx')],
            },
        ),
    ]
