# Generated by Django 6.0.3 on 2026-03-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
